name: curious_hub_app
version: 0.0.1+1
description: "Yet another GitHub client"
publish_to: "none"
resolution: workspace

environment:
  flutter: ">=3.41.4"
  sdk: ^3.11.1

dependencies:
  auto_route: ^11.1.0
  curious_hub_core: ^0.0.1
  curious_hub_i18n: ^0.0.1
  dio: ^5.9.2
  drift: ^2.31.0
  drift_dev: ^2.31.0
  drift_flutter: ^0.2.8
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  gitsumu: ^0.7.3
  hooks_riverpod: ^3.1.0
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2906.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  smooth_sheets: ^0.17.0
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.42
  system_theme: ^3.2.0
  talker: ^5.1.15
  talker_flutter: ^5.1.15
  url_launcher: ^6.3.2

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.13.0
  custom_lint: ^0.8.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  pyramid_lint: ^2.4.0
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0
  slang_build_runner: ^4.14.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
